name: Build and Package Jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: create wrapper
      run: mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=3.8.1
      
    - name: Make Maven Wrapper Executable
      run: chmod +x mvnw
      working-directory: autoDeploy

    

    - name: Build and Package Jar
      run: ./mvnw clean install -DskipTests=true
      working-directory: autoDeploy

    - name: Upload Jar
      uses: actions/upload-artifact@v2
      with:
        path: autoDeploy/target/*.jar
