on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          mvn clean install autoDeploy/blob/main/autoDeploy/pom.xml
          shell: cmd
          
