name: Continuous Deployement

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B clean install --file autoDeploy/pom.xml

    #- name: Upload JAR file
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: autoDeploy
    #    path: autoDeploy/target/*.jar

    - name: Deployment
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        password: ${{ secrets.STAGING_PASSWORD }}
        username: ${{ secrets.SSH_USERNAME }}
        source: "autoDeploy/target/*.jar"
        target: "/unicorn-manager/"
        #run: |
         # apt install sshpass
        #  sshpass -p ${{ secrets.STAGING_PASSWORD }} scp -p 22 *.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.STAGING_HOST }}:/home/aviotti/unicorn-manager 

        #  cd unicorn-manager
       #   ls
       #   scp -r -p 22 *.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.STAGING_HOST }}:/home/aviotti/unicorn-manager
           
