on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: action-maven
  # You may pin to the exact commit or the version.
  # uses: comchangs/action-maven@54db702e085ac767dad94c87e84499afb9d77162
        uses: comchangs/action-maven@v0.4-beta
          
