on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: comchangs/action-maven@54db702e085ac767dad94c87e84499afb9d77162
          
