name: Continuous Deployement

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B clean install --file autoDeploy/pom.xml

    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      with:
        name: autoDeploy
        path: autoDeploy/target/*.jar

    - name: Download JAR artifact
      uses: actions/download-artifact@v2
      with:
        name: autoDeploy
        path: artifacts

    - name: Deploy to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.STAGING_HOST }}
        password: ${{ secrets.STAGING_PASSWORD }}
        username: ${{ secrets.SSH_USERNAME }}
        source: "artifacts/*.jar"
        target: "/unicorn-manager-test-01/"
        #target: /home/aviotti/unicorn-manager-test-01/
