name: Build JAR with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B clean install --file autoDeploy/pom.xml

    - name: List contents of target directory
      run: ls -R autoDeploy/target

    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      with:
        name: autoDeploy
        path: target/autoDeploy-1.0.jar
